// ─── Curated personal growth resources ────────────────────────────────────────
// Every item here is a real, verifiable resource.
// isCurated = true flags it for the "Editor's Pick" badge and feed priority.
// source = "Curated" differentiates it from API-sourced content in the UI.
//
// subcategory values must exactly match keys in SUBTOPIC_META (src/data.js):
//   relationships: communication | boundaries | emotional intimacy | self-worth | conflict resolution
//   stress:        burnout recovery | sleep & anxiety | anxiety & worry | everyday stress | resilience building
//   career:        career change | confidence & assertiveness | job search & interviews | leadership & management | work-life balance
//   finance:       financial anxiety | budgeting & saving | investing & stocks | real estate | debt & credit
//   parenting:     toddler behaviour | teen years | school & learning | parent wellbeing | family dynamics
//   productivity:  focus & flow | time management | habit building | procrastination & motivation | digital minimalism

export const CURATED_ITEMS = [

  // ── Apps ─────────────────────────────────────────────────────────────────────

  {
    id: "cur-app-headspace",
    title: "Headspace",
    type: "app",
    category: "stress",
    subcategory: "everyday stress",
    method: "mindfulness",
    priceType: "paid",
    price: "$12.99/mo",
    rating: 4.8,
    ratingCount: 600000,
    description: "Guided meditation and mindfulness app developed with Oxford University researchers. Covers sleep, stress, focus, and anxiety with structured beginner to advanced programmes.",
    thumbnail: null,
    link: "https://www.headspace.com",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-app-calm",
    title: "Calm",
    type: "app",
    category: "stress",
    subcategory: "sleep & anxiety",
    method: "mindfulness",
    priceType: "paid",
    price: "$14.99/mo",
    rating: 4.8,
    ratingCount: 1800000,
    description: "Sleep stories, breathing exercises, and guided meditations designed to reduce anxiety and improve sleep quality. The #1 app for sleep and meditation on the App Store.",
    thumbnail: null,
    link: "https://www.calm.com",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-app-insight-timer",
    title: "Insight Timer",
    type: "app",
    category: "stress",
    subcategory: "everyday stress",
    method: "mindfulness",
    priceType: "free",
    price: null,
    rating: 4.9,
    ratingCount: 330000,
    description: "The world's largest free library of guided meditations, with over 130,000 sessions from 10,000+ teachers. Includes live events, courses, and ambient music for every mood.",
    thumbnail: null,
    link: "https://insighttimer.com",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-app-ynab",
    title: "YNAB (You Need A Budget)",
    type: "app",
    category: "finance",
    subcategory: "budgeting & saving",
    method: "coaching",
    priceType: "paid",
    price: "$14.99/mo",
    rating: 4.7,
    ratingCount: 178000,
    description: "Zero-based budgeting app that assigns every dollar a job before you spend it. Users report saving over $600 in their first two months on average. Used by millions worldwide.",
    thumbnail: null,
    link: "https://www.ynab.com",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-app-fabulous",
    title: "Fabulous: Daily Habit Tracker",
    type: "app",
    category: "productivity",
    subcategory: "habit building",
    method: "coaching",
    priceType: "paid",
    price: "$9.99/mo",
    rating: 4.7,
    ratingCount: 440000,
    description: "Science-based habit and routine builder developed with Duke University's Behavioural Economics Lab. Uses motivational interviewing and CBT to make routines stick long-term.",
    thumbnail: null,
    link: "https://www.thefabulous.co",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-app-forest",
    title: "Forest: Focus for Productivity",
    type: "app",
    category: "productivity",
    subcategory: "focus & flow",
    method: "coaching",
    priceType: "paid",
    price: "$3.99",
    rating: 4.8,
    ratingCount: 1400000,
    description: "Stay focused by growing a virtual tree — leave the app and it dies. Partners with Trees for the Future to plant real trees when you reach focus milestones.",
    thumbnail: null,
    link: "https://www.forestapp.cc",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-app-betterhelp",
    title: "BetterHelp",
    type: "app",
    category: "stress",
    subcategory: "anxiety & worry",
    method: "therapy",
    priceType: "paid",
    price: "$60–$100/wk",
    rating: 4.5,
    ratingCount: 33000,
    description: "Online therapy platform connecting you with a licensed therapist via text, phone, and video. The world's largest e-counselling service with 30,000+ therapists across every specialty.",
    thumbnail: null,
    link: "https://www.betterhelp.com",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-app-rescuetime",
    title: "RescueTime",
    type: "app",
    category: "productivity",
    subcategory: "digital minimalism",
    method: "coaching",
    priceType: "paid",
    price: "$12/mo",
    rating: 4.4,
    ratingCount: 8000,
    description: "Automatically tracks how you spend time across apps and websites, giving you an honest picture of your digital habits and detailed reports on where your focus actually goes.",
    thumbnail: null,
    link: "https://www.rescuetime.com",
    source: "Curated",
    isCurated: true,
  },

  // ── Coaches ───────────────────────────────────────────────────────────────────

  {
    id: "cur-coach-tony-robbins",
    title: "Tony Robbins",
    type: "coach",
    category: "career",
    subcategory: "confidence & assertiveness",
    method: "NLP",
    priceType: "paid",
    price: null,
    rating: 4.8,
    ratingCount: null,
    description: "World-renowned performance coach, best-selling author, and philanthropist. Known for NLP-based techniques for peak performance, business growth, and lasting mindset transformation.",
    thumbnail: null,
    link: "https://www.tonyrobbins.com",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-coach-brene-brown",
    title: "Brené Brown",
    type: "coach",
    category: "relationships",
    subcategory: "emotional intimacy",
    method: "therapy",
    priceType: "paid",
    price: null,
    rating: 4.9,
    ratingCount: null,
    description: "Research professor and storyteller whose 20-year study on vulnerability, courage, and shame has reshaped how leaders communicate. Author of Daring Greatly and Atlas of the Heart.",
    thumbnail: null,
    link: "https://brenebrown.com",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-coach-esther-perel",
    title: "Esther Perel",
    type: "coach",
    category: "relationships",
    subcategory: "communication",
    method: "therapy",
    priceType: "paid",
    price: null,
    rating: 4.9,
    ratingCount: null,
    description: "Psychotherapist and internationally recognised authority on modern relationships. Author of Mating in Captivity and host of the Where Should We Begin? podcast. Practices in 12 languages.",
    thumbnail: null,
    link: "https://www.estherperel.com",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-coach-mel-robbins",
    title: "Mel Robbins",
    type: "coach",
    category: "productivity",
    subcategory: "procrastination & motivation",
    method: "coaching",
    priceType: "paid",
    price: null,
    rating: 4.8,
    ratingCount: null,
    description: "Motivational speaker and author of The 5 Second Rule. Helps people overcome procrastination, build confidence, and take action using neuroscience-backed techniques anyone can apply.",
    thumbnail: null,
    link: "https://melrobbins.com",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-coach-jay-shetty",
    title: "Jay Shetty",
    type: "coach",
    category: "stress",
    subcategory: "resilience building",
    method: "mindfulness",
    priceType: "paid",
    price: null,
    rating: 4.7,
    ratingCount: null,
    description: "Former monk turned purpose coach and bestselling author of Think Like a Monk. Host of On Purpose, one of the world's top mental health podcasts with over 500 million downloads.",
    thumbnail: null,
    link: "https://jayshetty.me",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-coach-matthew-hussey",
    title: "Matthew Hussey",
    type: "coach",
    category: "relationships",
    subcategory: "self-worth",
    method: "coaching",
    priceType: "paid",
    price: null,
    rating: 4.7,
    ratingCount: null,
    description: "Relationship coach and New York Times bestselling author. Helps people build confidence, overcome patterns of self-sabotage, and create deeply fulfilling relationships from the inside out.",
    thumbnail: null,
    link: "https://www.matthewhussey.com",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-coach-marie-forleo",
    title: "Marie Forleo",
    type: "coach",
    category: "career",
    subcategory: "career change",
    method: "coaching",
    priceType: "paid",
    price: null,
    rating: 4.8,
    ratingCount: null,
    description: "Business and life coach named by Oprah as a thought leader for the next generation. Creator of B-School, an online business programme taken by 80,000+ entrepreneurs in 159 countries.",
    thumbnail: null,
    link: "https://www.marieforleo.com",
    source: "Curated",
    isCurated: true,
  },

  // ── Retreats ──────────────────────────────────────────────────────────────────

  {
    id: "cur-retreat-esalen",
    title: "Esalen Institute",
    type: "retreat",
    category: "stress",
    subcategory: "burnout recovery",
    method: "mindfulness",
    priceType: "paid",
    price: "From $350/night",
    rating: 4.8,
    ratingCount: null,
    description: "Iconic residential retreat on the Big Sur cliffs in California. Offers hundreds of workshops in mindfulness, somatic practices, depth psychology, and personal transformation each year.",
    thumbnail: null,
    link: "https://www.esalen.org",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-retreat-kripalu",
    title: "Kripalu Center for Yoga & Health",
    type: "retreat",
    category: "stress",
    subcategory: "everyday stress",
    method: "mindfulness",
    priceType: "paid",
    price: "From $250/night",
    rating: 4.7,
    ratingCount: null,
    description: "The largest yoga and holistic health retreat in North America, in the Berkshires of Massachusetts. Programmes range from weekend yoga immersions to week-long mind-body healing retreats.",
    thumbnail: null,
    link: "https://kripalu.org",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-retreat-omega",
    title: "Omega Institute for Holistic Studies",
    type: "retreat",
    category: "relationships",
    subcategory: "emotional intimacy",
    method: "therapy",
    priceType: "paid",
    price: "From $180/night",
    rating: 4.7,
    ratingCount: null,
    description: "Leading holistic learning centre in Rhinebeck, New York. Hosts workshops with world-class teachers in relationships, trauma healing, creativity, and spiritual intelligence.",
    thumbnail: null,
    link: "https://www.eomega.org",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-retreat-vipassana",
    title: "Vipassana 10-Day Silent Retreat",
    type: "retreat",
    category: "stress",
    subcategory: "everyday stress",
    method: "mindfulness",
    priceType: "free",
    price: null,
    rating: 4.9,
    ratingCount: null,
    description: "10-day silent meditation retreats in the tradition of S.N. Goenka, offered at 300+ centres worldwide at no charge. One of the most widely attended and transformative retreat formats globally.",
    thumbnail: null,
    link: "https://www.dhamma.org",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-retreat-hoffman",
    title: "The Hoffman Process",
    type: "retreat",
    category: "relationships",
    subcategory: "emotional intimacy",
    method: "therapy",
    priceType: "paid",
    price: "From $5,600",
    rating: 4.9,
    ratingCount: null,
    description: "Intensive 7-day residential programme addressing negative behavioural patterns rooted in childhood. Widely endorsed by therapists, CEOs, and researchers. Over 150,000 graduates in 14 countries.",
    thumbnail: null,
    link: "https://www.hoffmaninstitute.org",
    source: "Curated",
    isCurated: true,
  },

  // ── Courses ────────────────────────────────────────────────────────────────────

  {
    id: "cur-course-science-wellbeing",
    title: "The Science of Well-Being",
    type: "course",
    category: "stress",
    subcategory: "resilience building",
    method: "therapy",
    priceType: "free",
    price: null,
    rating: 4.9,
    ratingCount: 3800000,
    description: "Yale University's most popular course ever, taught by Prof. Laurie Santos. Evidence-based science of happiness: why we think we know what makes us happy and what actually does.",
    thumbnail: null,
    link: "https://www.coursera.org/learn/the-science-of-well-being",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-course-financial-peace",
    title: "Financial Peace University",
    type: "course",
    category: "finance",
    subcategory: "budgeting & saving",
    method: "coaching",
    priceType: "paid",
    price: "$79.99",
    rating: 4.8,
    ratingCount: null,
    description: "Dave Ramsey's step-by-step programme for eliminating debt, building savings, and investing. Delivered in nine video lessons with a structured plan used by over 10 million people.",
    thumbnail: null,
    link: "https://www.ramseysolutions.com/ramseyplus/financial-peace",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-course-dare-to-lead",
    title: "Dare to Lead™",
    type: "course",
    category: "career",
    subcategory: "leadership & management",
    method: "coaching",
    priceType: "paid",
    price: "$595",
    rating: 4.9,
    ratingCount: null,
    description: "Brené Brown's research-based leadership programme focused on courage, vulnerability, and building cultures of trust. Designed for senior leaders and taken by Fortune 500 executive teams.",
    thumbnail: null,
    link: "https://brenebrown.com/hubs/dare-to-lead",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-course-learning-how-to-learn",
    title: "Learning How to Learn",
    type: "course",
    category: "productivity",
    subcategory: "habit building",
    method: "coaching",
    priceType: "free",
    price: null,
    rating: 4.8,
    ratingCount: 3100000,
    description: "The world's most-enrolled online course, by Barbara Oakley and Terrence Sejnowski. Neuroscience-backed methods for retaining information, overcoming procrastination, and building mental stamina.",
    thumbnail: null,
    link: "https://www.coursera.org/learn/learning-how-to-learn",
    source: "Curated",
    isCurated: true,
  },

  // ── Workshops ─────────────────────────────────────────────────────────────────

  {
    id: "cur-workshop-gottman",
    title: "The Art and Science of Love",
    type: "workshop",
    category: "relationships",
    subcategory: "conflict resolution",
    method: "therapy",
    priceType: "paid",
    price: "From $500/couple",
    rating: 4.9,
    ratingCount: null,
    description: "The Gottman Institute's evidence-based couples workshop, grounded in 40+ years of relationship research. Taught worldwide by certified therapists and used as part of clinical treatment.",
    thumbnail: null,
    link: "https://www.gottman.com/couples/workshops",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-workshop-upw",
    title: "Unleash the Power Within (UPW)",
    type: "workshop",
    category: "career",
    subcategory: "confidence & assertiveness",
    method: "NLP",
    priceType: "paid",
    price: "From $650",
    rating: 4.7,
    ratingCount: null,
    description: "Tony Robbins' flagship 4-day live event combining NLP, state conditioning, and experiential exercises. Attended by over 5 million people across 100+ countries since 1983.",
    thumbnail: null,
    link: "https://www.tonyrobbins.com/events/unleash-the-power-within",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-workshop-byron-katie",
    title: "The Work of Byron Katie",
    type: "workshop",
    category: "stress",
    subcategory: "anxiety & worry",
    method: "therapy",
    priceType: "paid",
    price: "From $295",
    rating: 4.8,
    ratingCount: null,
    description: "A self-inquiry method for examining the stressful thoughts that cause suffering. Workshop participants learn to question beliefs at their root. Practised in 120+ countries and taught in schools and prisons.",
    thumbnail: null,
    link: "https://thework.com",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-workshop-positive-intelligence",
    title: "Positive Intelligence (PQ) Mental Fitness",
    type: "workshop",
    category: "productivity",
    subcategory: "procrastination & motivation",
    method: "coaching",
    priceType: "paid",
    price: "$995",
    rating: 4.7,
    ratingCount: null,
    description: "6-week mental fitness programme by Shirzad Chamine, Stanford lecturer and CEO coach. Strengthens the positive brain through daily practice. Widely used by Fortune 500 executives and coaches.",
    thumbnail: null,
    link: "https://www.positiveintelligence.com",
    source: "Curated",
    isCurated: true,
  },

  // ── Finance (additional) ──────────────────────────────────────────────────────

  {
    id: "cur-coach-ramit-sethi",
    title: "Ramit Sethi",
    type: "coach",
    category: "finance",
    subcategory: "budgeting & saving",
    method: "coaching",
    priceType: "paid",
    price: null,
    rating: 4.8,
    ratingCount: null,
    description: "Personal finance expert and author of the New York Times bestseller I Will Teach You to Be Rich. Known for automating finances, negotiating salary, and building wealth without cutting lattes.",
    thumbnail: null,
    link: "https://www.iwillteachyoutoberich.com",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-app-acorns",
    title: "Acorns",
    type: "app",
    category: "finance",
    subcategory: "investing & stocks",
    method: "coaching",
    priceType: "paid",
    price: "$3/mo",
    rating: 4.7,
    ratingCount: 812000,
    description: "Micro-investing app that rounds up everyday purchases and automatically invests the spare change into diversified ETF portfolios. Used by over 9 million investors, including beginners.",
    thumbnail: null,
    link: "https://www.acorns.com",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-app-empower",
    title: "Empower Personal Dashboard",
    type: "app",
    category: "finance",
    subcategory: "budgeting & saving",
    method: "coaching",
    priceType: "free",
    price: null,
    rating: 4.7,
    ratingCount: 43000,
    description: "Free financial dashboard (formerly Personal Capital) that links all your accounts to track net worth, spending, and investment performance in one place. Used by over 3 million people.",
    thumbnail: null,
    link: "https://www.empower.com/personal-finance-tools",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-course-money-master-game",
    title: "Tony Robbins Money: Master the Game",
    type: "course",
    category: "finance",
    subcategory: "investing & stocks",
    method: "coaching",
    priceType: "paid",
    price: "$49",
    rating: 4.6,
    ratingCount: null,
    description: "Based on Tony Robbins' bestselling book of the same name, this programme distils interviews with 50 of the world's top investors into an actionable path to financial freedom.",
    thumbnail: null,
    link: "https://www.tonyrobbins.com/products/money-master-the-game",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-workshop-financial-gym",
    title: "The Financial Gym",
    type: "workshop",
    category: "finance",
    subcategory: "financial anxiety",
    method: "coaching",
    priceType: "paid",
    price: "From $85/mo",
    rating: 4.8,
    ratingCount: null,
    description: "One-on-one financial coaching membership where certified financial trainers help you tackle debt, build savings, and overcome money anxiety with a personalised plan.",
    thumbnail: null,
    link: "https://financialgym.com",
    source: "Curated",
    isCurated: true,
  },

  // ── Parenting ─────────────────────────────────────────────────────────────────

  {
    id: "cur-coach-janet-lansbury",
    title: "Janet Lansbury",
    type: "coach",
    category: "parenting",
    subcategory: "toddler behaviour",
    method: "therapy",
    priceType: "free",
    price: null,
    rating: 4.9,
    ratingCount: null,
    description: "Internationally recognised parenting adviser and author of No Bad Kids and Elevating Child Care. Teaches the RIE approach — respectful parenting that helps toddlers build confidence and self-regulation.",
    thumbnail: null,
    link: "https://www.janetlansbury.com",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-coach-dan-siegel",
    title: "Dr. Daniel J. Siegel",
    type: "coach",
    category: "parenting",
    subcategory: "family dynamics",
    method: "therapy",
    priceType: "paid",
    price: null,
    rating: 4.9,
    ratingCount: null,
    description: "Clinical professor of psychiatry at UCLA and author of The Whole-Brain Child and No-Drama Discipline. Pioneered the use of neuroscience to help parents understand and connect with their children's minds.",
    thumbnail: null,
    link: "https://www.drdansiegel.com",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-course-positive-parenting",
    title: "Positive Parenting Solutions",
    type: "course",
    category: "parenting",
    subcategory: "toddler behaviour",
    method: "coaching",
    priceType: "paid",
    price: "$247",
    rating: 4.8,
    ratingCount: null,
    description: "Amy McCready's online parenting course used by over 100,000 families. Teaches proactive strategies for reducing power struggles, misbehaviour, and parental burnout — without yelling or punishment.",
    thumbnail: null,
    link: "https://www.positiveparentingsolutions.com",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-coach-laura-markham",
    title: "Dr. Laura Markham",
    type: "coach",
    category: "parenting",
    subcategory: "parent wellbeing",
    method: "therapy",
    priceType: "free",
    price: null,
    rating: 4.8,
    ratingCount: null,
    description: "Clinical psychologist and author of Peaceful Parent, Happy Kids. Founder of AhaParenting.com — one of the most-visited parenting resources online, focused on connection-based discipline.",
    thumbnail: null,
    link: "https://www.ahaparenting.com",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-course-gottman-parenting",
    title: "Emotion Coaching — The Gottman Institute",
    type: "course",
    category: "parenting",
    subcategory: "family dynamics",
    method: "therapy",
    priceType: "paid",
    price: "$99",
    rating: 4.8,
    ratingCount: null,
    description: "Online course teaching Dr. John Gottman's Emotion Coaching method — a research-backed approach for raising emotionally intelligent children who handle stress, friendships, and conflict effectively.",
    thumbnail: null,
    link: "https://www.gottman.com/parents",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-app-big-life-journal",
    title: "Big Life Journal",
    type: "app",
    category: "parenting",
    subcategory: "school & learning",
    method: "coaching",
    priceType: "paid",
    price: "$9.99/mo",
    rating: 4.8,
    ratingCount: null,
    description: "Growth mindset journal and app for kids aged 4–18, developed with child psychologists. Used in over 150 countries and 20,000+ schools to build resilience, confidence, and love of learning.",
    thumbnail: null,
    link: "https://biglifejournal.com",
    source: "Curated",
    isCurated: true,
  },
  {
    id: "cur-retreat-parent-child",
    title: "Hand in Hand Parenting",
    type: "workshop",
    category: "parenting",
    subcategory: "toddler behaviour",
    method: "therapy",
    priceType: "paid",
    price: "From $97",
    rating: 4.7,
    ratingCount: null,
    description: "Workshop-based parenting approach developed by Patty Wipfler that teaches listening tools, playful parenting, and special one-on-one time to reduce aggression, tantrums, and sibling conflict.",
    thumbnail: null,
    link: "https://www.handinhandparenting.org",
    source: "Curated",
    isCurated: true,
  },
];
